/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --types /Users/ebowwa/simulation/public/models/a_book_of_poems.glb 
Author: aqpetteri (https://sketchfab.com/aqpetteri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-book-of-poems-5bcbbf682a12409687671a6954d99021
Title: A Book Of Poems
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type Length = {
 [key: string]: number;
};

type GLTFResult = GLTF & {
 nodes: {
   mesh_2: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_3: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_4: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_5: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_6: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_7: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_8: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_9: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_10: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_11: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_12: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_13: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_14: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_15: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_16: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_17: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_18: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_19: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_20: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_21: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   mesh_22: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_4: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_6: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_50: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_52: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_54: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_56: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_58: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_60: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_62: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_64: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
   Object_66: THREE.Mesh & { geometry: THREE.BufferGeometry & { length: number } }
 }
 materials: {
   Snow: THREE.MeshBasicMaterial
   Holdout: THREE.MeshBasicMaterial
   Book: THREE.MeshBasicMaterial
   Terrain: THREE.MeshBasicMaterial
   Bush: THREE.MeshBasicMaterial
   material: THREE.MeshBasicMaterial
   LightCone: THREE.MeshBasicMaterial
 }
 animations: GLTFAction[]
}

type ActionName = 'Animation'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/a_book_of_poems.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Snow_24" position={[-4.893, 1.669, 0.075]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials.Snow} />
              </group>
              <group name="Snow001_25" position={[-4.556, 0.49, -0.372]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials.Snow} />
              </group>
              <group name="Snow002_26" position={[-4.9, 0.978, 1.014]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={materials.Snow} />
              </group>
              <group name="Snow003_27" position={[-6.107, 0.934, -0.555]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_5" geometry={nodes.mesh_5.geometry} material={materials.Snow} />
              </group>
              <group name="Snow004_28" position={[-5.469, 0.91, -0.412]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_6" geometry={nodes.mesh_6.geometry} material={materials.Snow} />
              </group>
              <group name="Snow005_29" position={[-3.945, 0.372, -0.293]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_7" geometry={nodes.mesh_7.geometry} material={materials.Snow} />
              </group>
              <group name="Snow006_30" position={[-4.859, 0.547, -1.552]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={materials.Snow} />
              </group>
              <group name="Snow007_31" position={[-4.52, 0.572, 1.003]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={materials.Snow} />
              </group>
              <group name="Snow008_32" position={[-4.893, 1.669, 0.075]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_10" geometry={nodes.mesh_10.geometry} material={materials.Snow} />
              </group>
              <group name="Snow009_33" position={[-4.556, 0.49, -0.372]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_11" geometry={nodes.mesh_11.geometry} material={materials.Snow} />
              </group>
              <group name="Snow010_34" position={[-4.9, 0.978, 1.014]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_12" geometry={nodes.mesh_12.geometry} material={materials.Snow} />
              </group>
              <group name="Snow011_35" position={[-6.107, 0.934, -0.555]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_13" geometry={nodes.mesh_13.geometry} material={materials.Snow} />
              </group>
              <group name="Snow012_36" position={[-5.469, 0.91, -0.412]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_14" geometry={nodes.mesh_14.geometry} material={materials.Snow} />
              </group>
              <group name="Snow013_37" position={[-3.945, 0.372, -0.293]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_15" geometry={nodes.mesh_15.geometry} material={materials.Snow} />
              </group>
              <group name="Snow014_38" position={[-4.859, 0.547, -1.552]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_16" geometry={nodes.mesh_16.geometry} material={materials.Snow} />
              </group>
              <group name="Snow015_39" position={[-4.52, 0.572, 1.003]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_17" geometry={nodes.mesh_17.geometry} material={materials.Snow} />
              </group>
              <group name="Snow016_40" position={[-2.347, 1.31, -1.388]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_18" geometry={nodes.mesh_18.geometry} material={materials.Snow} />
              </group>
              <group name="Snow017_41" position={[-1.661, 1.789, -0.684]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_19" geometry={nodes.mesh_19.geometry} material={materials.Snow} />
              </group>
              <group name="Snow018_42" position={[-2.701, 0.935, -1.132]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_20" geometry={nodes.mesh_20.geometry} material={materials.Snow} />
              </group>
              <group name="Snow019_43" position={[-1.012, 1.134, -1.165]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_21" geometry={nodes.mesh_21.geometry} material={materials.Snow} />
              </group>
              <group name="Snow020_44" position={[-0.448, 1.127, -0.224]} rotation={[0, Math.PI / 2, 0]} scale={0.024}>
                <mesh name="mesh_22" geometry={nodes.mesh_22.geometry} material={materials.Snow} />
              </group>
              <group name="Holdout_2" position={[-4.636, 0, 0]} scale={6.368}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Holdout} />
              </group>
              <group name="Pages002_5" position={[0.03, 0.795, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Book} />
              </group>
              <group name="Ground_low_45" position={[-8.569, -0.226, -0.277]} rotation={[0, Math.PI / 2, 0]} scale={[7.214, 8.8, 8.8]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Terrain} />
              </group>
              <group name="bush001_46" position={[-5.477, 0.33, -1.891]} rotation={[1.912, -0.006, -1.597]} scale={0.435}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Bush} />
              </group>
              <group name="bush002_47" position={[-7.216, 0.401, -1.194]} rotation={[0.977, -0.01, -1.526]} scale={0.435}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Bush} />
              </group>
              <group name="bush003_48" position={[-10.506, 0.401, 0.864]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.215}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Bush} />
              </group>
              <group name="bush004_49" position={[-10.978, 0.638, 0.614]} rotation={[2.013, -0.052, -1.887]} scale={0.215}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Bush} />
              </group>
              <group name="bush005_50" position={[-7.696, 0.291, -2.728]} rotation={[1.791, -0.003, -1.588]} scale={0.649}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Bush} />
              </group>
              <group name="bush_51" position={[-10.508, 0.018, 1.469]} rotation={[0.704, -0.024, -1.51]} scale={0.389}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Bush} />
              </group>
              <group name="Sphere_52" position={[-6.259, -0.226, -0.057]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={13.841}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material} />
              </group>
              <group name="LightCone_53" position={[-15.353, 2.677, 1.139]} rotation={[1.529, 0.344, 0.824]} scale={0.8}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.LightCone} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/a_book_of_poems.glb')
