/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Player.glb -t -o src/components/three/assets/mario/PlayerTyped.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'idle' | 'walk' | 'run' | 'jump' | 'land' | 'fall' | 'die'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Face00__MarioFaceMat00: THREE.SkinnedMesh
    Face00__MarioHigeMat00: THREE.SkinnedMesh
    Mario__MarioBodyMat00: THREE.SkinnedMesh
    Mario__MarioBodyMat01: THREE.SkinnedMesh
    Mario__MarioFaceMat00: THREE.SkinnedMesh
    Mario__MarioMetalMat00: THREE.SkinnedMesh
    Mario__MarioShoesMat00: THREE.SkinnedMesh
    Eyeball__MarioEyeMat00: THREE.SkinnedMesh
    HandL00__MarioHandMat00: THREE.SkinnedMesh
    HandR00__MarioHandMat00: THREE.SkinnedMesh
    Hip: THREE.Bone
    Spine1: THREE.Bone
    Face00: THREE.Bone
    Eyeball: THREE.Bone
    HandL00: THREE.Bone
    HandR00: THREE.Bone
  }
  materials: {
    MarioFaceMat00: THREE.MeshStandardMaterial
    MarioHigeMat00: THREE.MeshStandardMaterial
    MarioBodyMat00: THREE.MeshStandardMaterial
    MarioBodyMat01: THREE.MeshStandardMaterial
    MarioMetalMat00: THREE.MeshStandardMaterial
    MarioShoesMat00: THREE.MeshStandardMaterial
    MarioEyeMat00: THREE.MeshStandardMaterial
    MarioHandMat00: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/Player.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Player">
        <group name="Player_1">
          <group name="Mario">
            <group name="AllRoot">
              <group name="JointRoot" position={[0, 0.611, -0.041]}>
                <primitive object={nodes.Hip} />
                <primitive object={nodes.Spine1} />
              </group>
            </group>
            <skinnedMesh name="Face00__MarioFaceMat00" geometry={nodes.Face00__MarioFaceMat00.geometry} material={materials.MarioFaceMat00} skeleton={nodes.Face00__MarioFaceMat00.skeleton}>
              <skinnedMesh name="Face00__MarioHigeMat00" geometry={nodes.Face00__MarioHigeMat00.geometry} material={materials.MarioHigeMat00} skeleton={nodes.Face00__MarioHigeMat00.skeleton} />
            </skinnedMesh>
            <skinnedMesh name="Mario__MarioBodyMat00" geometry={nodes.Mario__MarioBodyMat00.geometry} material={materials.MarioBodyMat00} skeleton={nodes.Mario__MarioBodyMat00.skeleton}>
              <skinnedMesh name="Mario__MarioBodyMat01" geometry={nodes.Mario__MarioBodyMat01.geometry} material={materials.MarioBodyMat01} skeleton={nodes.Mario__MarioBodyMat01.skeleton} />
              <skinnedMesh name="Mario__MarioFaceMat00" geometry={nodes.Mario__MarioFaceMat00.geometry} material={materials.MarioMetalMat00} skeleton={nodes.Mario__MarioFaceMat00.skeleton} />
              <skinnedMesh name="Mario__MarioMetalMat00" geometry={nodes.Mario__MarioMetalMat00.geometry} material={materials.MarioMetalMat00} skeleton={nodes.Mario__MarioMetalMat00.skeleton} />
              <skinnedMesh name="Mario__MarioShoesMat00" geometry={nodes.Mario__MarioShoesMat00.geometry} material={materials.MarioShoesMat00} skeleton={nodes.Mario__MarioShoesMat00.skeleton} />
            </skinnedMesh>
            <skinnedMesh name="Eyeball__MarioEyeMat00" geometry={nodes.Eyeball__MarioEyeMat00.geometry} material={materials.MarioEyeMat00} skeleton={nodes.Eyeball__MarioEyeMat00.skeleton} />
            <skinnedMesh name="HandL00__MarioHandMat00" geometry={nodes.HandL00__MarioHandMat00.geometry} material={materials.MarioHandMat00} skeleton={nodes.HandL00__MarioHandMat00.skeleton} />
            <skinnedMesh name="HandR00__MarioHandMat00" geometry={nodes.HandR00__MarioHandMat00.geometry} material={materials.MarioHandMat00} skeleton={nodes.HandR00__MarioHandMat00.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Player.glb')
